require("blocks/item");
require("blocks/liquid");
require("blocks/power");
require("blocks/wall");
require("blocks/turret");
require("blocks/value");
require("blocks/unit");
require("blocks/magic");
require("blocks/conv");
require("blocks/shield");
require("blocks/project");
print("$$$$$$$$$$$$$$$$$$$");
print("Загружено: 11 скрипта");
print("$$$$$$$$$$$$$$$$$$$");