require("blocks/item");
require("blocks/liquid");
require("blocks/power");
require("blocks/wall");
require("blocks/turret");
require("blocks/value");
require("blocks/unit");
require("blocks/magic");
require("blocks/conveyor");
print("$$$$$$$$$$$$$$$$$$$");
print("Загружено: 9 скрипта");
print("$$$$$$$$$$$$$$$$$$$");