require("blocks/item");
require("blocks/liquid");
require("blocks/power");
require("blocks/wall");
require("blocks/turret");
require("blocks/value");
require("blocks/unit");
require("blocks/magic");
print("$$$$$$$$$$$$$$$$$$$");
print("Загружено: 8 скрипта");
print("$$$$$$$$$$$$$$$$$$$");